// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUDNXCN5doJdb6e8INZTnLEJtLcTd5bFU',
    appId: '1:458643805580:web:dfd3867f4442ed0222f2a9',
    messagingSenderId: '458643805580',
    projectId: 'project-validad',
    authDomain: 'project-validad.firebaseapp.com',
    storageBucket: 'project-validad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB-xeT8MYiaCl5mb-cN9C46JANczQamb8',
    appId: '1:458643805580:android:f877c8f1c2e3e4b822f2a9',
    messagingSenderId: '458643805580',
    projectId: 'project-validad',
    storageBucket: 'project-validad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgfqx3HiiAknQ-ED1okfJTn_zJtDySOO4',
    appId: '1:458643805580:ios:c2a059fae54b66da22f2a9',
    messagingSenderId: '458643805580',
    projectId: 'project-validad',
    storageBucket: 'project-validad.appspot.com',
    iosBundleId: 'com.example.projetoValid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgfqx3HiiAknQ-ED1okfJTn_zJtDySOO4',
    appId: '1:458643805580:ios:13216409019d277122f2a9',
    messagingSenderId: '458643805580',
    projectId: 'project-validad',
    storageBucket: 'project-validad.appspot.com',
    iosBundleId: 'com.example.projetoValid.RunnerTests',
  );
}
